# Generated by Django 4.0.1 on 2022-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformapicall',
            name='requested_data',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='platformapicall',
            name='requested_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='platformapicall',
            name='response_data',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
