# Generated by Django 4.0.1 on 2022-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_amount_product_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_amount',
            field=models.IntegerField(),
        ),
    ]
